spring:
  config:
    import: file:.env[.properties]

  application:
    name: ${SPRING_APPLICATION_NAME}

  logging:
    level:
      root: ${SPRING_LOGGING_LEVEL_ROOT}
      org.springframework: ${SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
      org.hibernate: ${SPRING_LOGGING_LEVEL_ORG_HIBERNATE}

  servlet:
    multipart:
      max-file-size: 5MB


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        use_sql_comments: ${SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS}
        default_batch_fetch_size: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_BATCH_FETCH_SIZE}

    logging:
      level:
        org.hibernate.SQL: ${SPRING_JPA_LOGGING_LEVEL_ORG_HIBERNATE_SQL}
        org.hibernate.type.descriptor.sql.BasicBinder: ${SPRING_JPA_LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER}